print = conn.write || print

// send a header
print('HTTP/1.0 200 OK\r\n');
print('Content-Type: text/html\r\n');
print('\r\n');

print("<html><body>\n");
print("<p>This example page is generated by the ");
print('<a href="https://github.com/civetweb/civetweb">CivetWeb web server</a>');
print(" with server side javascript.</p>\n");

var d = new Date();
var n = d.toString(); 

print("<p>Server time: " + n + "</p>\n");

print("</body></html>\n");

