print = conn.write || print

opts = [
"cgi_pattern",
"cgi_environment",
"put_delete_auth_file",
"cgi_interpreter",
"protect_uri",
"authentication_domain",
"ssi_pattern",
"throttle",
"access_log_file",
"enable_directory_listing",
"error_log_file",
"global_auth_file",
"index_files",
"enable_keep_alive",
"access_control_list",
"extra_mime_types",
"listening_ports",
"document_root",
"ssl_certificate",
"num_threads",
"run_as_user",
"url_rewrite_patterns",
"hide_files_patterns",
"request_timeout_ms",
"websocket_timeout_ms",
"decode_url",
"lua_preload_file",
"lua_script_pattern",
"lua_server_page_pattern",
"_experimental_duktape_script_pattern",
"websocket_root",
"lua_websocket_pattern",
"access_control_allow_origin",
"error_pages",
"_unknown__option"
]

// send a header
print('HTTP/1.0 200 OK\r\n');
print('Content-Type: text/html\r\n');
print('\r\n');

print("<html><body>\n");
print("<p>This example page is generated by the ");
print('<a href="https://github.com/civetweb/civetweb">CivetWeb web server</a>');
print(" with server side javascript.</p>\n");

for (var i=0; i < opts.length; i++) {
  var o = opts[i];
  var n = civetweb.getoption(o);
  if (typeof(n) == "string") {
    print("<p>Option " + o + " = " + n + "</p>\n");
  } else {
    print("<p>Option " + o + " not known</p>\n");
  }
}

print("</body></html>\n");
