require("cURL")

describe("civetweb basic", function()
 it("should serve a simple get request", function()
   assert.is_true(true)
 end)
 it("should fail the build on a failed test", function()
   assert.is_false(true)
 end)
end)
